# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: DEV-Gunbbang-Server CI

on:
  push:
   branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    # 1) 워크플로우 실행 전 기본적으로 체크아웃 필요
    - name: checkout
      uses: actions/checkout@v3
    
    # 2) JDK 21버전 설치, 다른 JDK 버전을 사용하다면 수정
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    # 3) 환경변수 파일 생성
    - name: make application.yml 파일 생성
      run: |
        pwd
        ## create application.yml in api module
        cd ./api/src/main/resources
        touch ./application.yml
        ls -al
        cd /home/runner/work/GEON-PPANG-SERVER/GEON-PPANG-SERVER
        
        
        ## create yml file in client/client-amplitude module
        mkdir ./client/client-amplitude/src/main/resources
        cd ./client/client-amplitude/src/main/resources
        touch ./client-amplitude.yml     
        ls -al
        cd /home/runner/work/GEON-PPANG-SERVER/GEON-PPANG-SERVER
        
        ## create yml file in client/client-apple module
        mkdir ./client/client-apple/src/main/resources
        cd ./client/client-apple/src/main/resources
        touch ./client-apple.yml     
        ls -al
        cd /home/runner/work/GEON-PPANG-SERVER/GEON-PPANG-SERVER
        
        
        ## create yml file in storage/db-core module
        mkdir ./storage/db-core/src/main/resources
        cd ./storage/db-core/src/main/resources
        touch ./storage-db-core.yml 
        ls -al
        cd /home/runner/work/GEON-PPANG-SERVER/GEON-PPANG-SERVER
        
        ## create yml file in support/slack module
        mkdir ./support/slack/src/main/resources
        cd ./support/slack/src/main/resources
        touch ./support-slack.yml 
        ls -al
        cd /home/runner/work/GEON-PPANG-SERVER/GEON-PPANG-SERVER
        
        
        # GitHub-Actions 에서 설정한 값을 application.yml 파일에 쓰기
        echo "${{ secrets.DEV_API_APPLICATION }}" >> ./api/src/main/resources/application.yml
        echo "${{ secrets.DEV_STORAGE_DB_CORE }}" >> ./storage/db-core/src/main/resources/storage-db-core.yml
        echo "${{ secrets.DEV_CLIENT_AMPLITUDE }}" >> ./client/client-amplitude/src/main/resources/client-amplitude.yml
        echo "${{ secrets.DEV_CLIENT_APPLE }}" >> ./client/client-apple/src/main/resources/client-apple.yml
        echo "${{ secrets.DEV_SUPPORT_SLACK }}" >> ./support/slack/src/main/resources/support-slack.yml
      
      shell: bash
        
    # 이 워크플로우는 gradle build
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle # 실제 application build(-x 옵션을 통해 test는 제외)
      run: ./gradlew build -x test
