# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Gunbbang-Server CI

on:
  push:
   branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    steps:
    # 1) 워크플로우 실행 전 기본적으로 체크아웃 필요
    - name: checkout
      uses: actions/checkout@v3
    
    # 2) JDK 11버전 설치, 다른 JDK 버전을 사용하다면 수정
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    # 3) 환경변수 파일 생성
    - name: make application.yml 파일 생성
      run: |
        pwd
        ## create application.yml in api module
        ## mkdir ./api/src/main/resources
        cd ./api/src/main/resources
        touch ./application.yml
        ls -al
        cd /home/runner/work/GEON-PPANG-SERVER/GEON-PPANG-SERVER
        
        
        ## create application.yml in client module
        mkdir ./client/client-feign/src/main/resources
        cd ./client/client-feign/src/main/resources
        touch ./application.yml
        touch ./client.yml     
        ls -al
        cd /home/runner/work/GEON-PPANG-SERVER/GEON-PPANG-SERVER
        
        
        ## create application.yml in storage module
        mkdir ./storage/db-core/src/main/resources
        cd ./storage/db-core/src/main/resources
        touch ./application.yml
        touch ./db-core.yml 
        ls -al
        cd /home/runner/work/GEON-PPANG-SERVER/GEON-PPANG-SERVER
        
        
        # GitHub-Actions 에서 설정한 값을 application.yml 파일에 쓰기
        echo "${{ secrets.PROD_API_APPLICATION_YML }}" >> ./api/src/main/resources/application.yml
        echo "${{ secrets.PROD_DB_CORE_APPLICATION_YML }}" >> ./storage/db-core/src/main/resources/application.yml
        echo "${{ secrets.PROD_DB_CORE }}" >> ./storage/db-core/src/main/resources/db-core.yml
        echo "${{ secrets.PROD_CLIENT }}" >> ./client/client-feign/src/main/resources/client.yml
        echo "${{ secrets.PROD_CLIENT_APPLICATION_YML }}" >> ./client/client-feign/src/main/resources/application.yml
        pwd
      
      shell: bash
        
    # 이 워크플로우는 gradle build
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle # 실제 application build(-x 옵션을 통해 test는 제외)
      run: ./gradlew build -x test
